name: Build with CMake and vcpkg

on:
  push:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  job:
    name: ${{ matrix.os }}-${{ github.workflow }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            triplet: x64-linux-static
          - os: macos-latest
            triplet: x64-osx-static
          - os: windows-latest
            triplet: x64-windows-static
    env:
      VCPKG_DEFAULT_TRIPLET: ${{ matrix.triplet }}
      BUILD_TYPE: Release
    steps:
      - uses: actions/checkout@v3
      - uses: lukka/get-cmake@latest
      - name: Setup vcpkg
        uses: lukka/run-vcpkg@main
        with:
          vcpkgCommitId: '501db0f17ef6df184fcdbfbe0f87cde2313b6ab1'
          vcpkgDirectory: '${{ runner.workspace }}/b/vcpkg'
      - name: Run CMake
        uses: lukka/run-cmake@main
        with:
          configurePreset: ninja-multi-vcpkg
          buildPreset: ninja-multi-vcpkg


